# Generated by Django 4.0 on 2021-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
